Repository Joxit/docker-registry-ui, pull requests merged in 2018-12, with the labels that each got.

#44 Improve documentation: traefik sample
  examples/traefik/README.md
  examples/traefik/acme.json
  examples/traefik/docker-compose-swarm.yml
  examples/traefik/run-swarm.sh
Labels: documentation

#58 New Feature: Overview of tag history content
  .gitignore
  src/images/docker-logo.svg
  src/index.html
  src/scripts/script.js
  src/scripts/static.js
  src/style.css
  src/tags/app.tag
  src/tags/catalog.tag
  src/tags/image-date.tag
  src/tags/remove-image.tag
  src/tags/remove.tag
  src/tags/tag-history-button.tag
  src/tags/tag-history.tag
  src/tags/taglist.tag
Labels: enhancement

#61 [Fix #59] image history, use v2 manifest instead of v1
  src/fonts/MaterialIcons-Regular.eot
  src/fonts/MaterialIcons-Regular.ttf
  src/fonts/MaterialIcons-Regular.woff
  src/fonts/MaterialIcons-Regular.woff2
  src/index.html
  src/scripts/http.js
  src/scripts/script.js
  src/style.css
  src/tags/app.tag
  src/tags/catalog.tag
  src/tags/copy-to-clipboard.tag
  src/tags/image-date.tag
  src/tags/image-size.tag
  src/tags/image-tag.tag
  src/tags/menu.tag
  src/tags/remove-image.tag
  src/tags/tag-history-button.tag
  src/tags/tag-history-element.tag
  src/tags/tag-history.tag
  src/tags/taglist.tag
Labels: high priority
